# fly.toml app configuration file generated for kexo-logger on 2023-08-22T10:08:29+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kexobotweb"
primary_region = "waw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true